/**
 * generated by http://RDFReactor.semweb4j.org ($Id: CodeGenerator.java 1535 2008-09-09 15:44:46Z max.at.xam.de $) on 4/10/15 20:45
 */
package es.us.isa.puri.model;

import org.ontoware.aifbcommons.collection.ClosableIterator;
import org.ontoware.rdf2go.exception.ModelRuntimeException;
import org.ontoware.rdf2go.model.Model;
import org.ontoware.rdf2go.model.node.BlankNode;
import org.ontoware.rdf2go.model.node.URI;
import org.ontoware.rdf2go.model.node.impl.URIImpl;
import org.ontoware.rdfreactor.runtime.Base;
import org.ontoware.rdfreactor.runtime.ReactorResult;

/**
 * This class manages access to these properties:
 * <ul>
 *   <li> HasRuleConclusion </li>
 *   <li> HasRulePremise </li>
 * </ul>
 *
 * This class was generated by <a href="http://RDFReactor.semweb4j.org">RDFReactor</a> on 4/10/15 20:45
 */
public class FuzzyRulePreference extends FuzzyPreference {

    /** http://www.isa.us.es/preferences#FuzzyRulePreference */
    @SuppressWarnings("hiding")
	public static final URI RDFS_CLASS = new URIImpl("http://www.isa.us.es/preferences#FuzzyRulePreference", false);

    /** http://www.isa.us.es/preferences#hasRuleConclusion */
    @SuppressWarnings("hiding")
	public static final URI HASRULECONCLUSION = new URIImpl("http://www.isa.us.es/preferences#hasRuleConclusion",false);

    /** http://www.isa.us.es/preferences#hasRulePremise */
    @SuppressWarnings("hiding")
	public static final URI HASRULEPREMISE = new URIImpl("http://www.isa.us.es/preferences#hasRulePremise",false);

    /** 
     * All property-URIs with this class as domain.
     * All properties of all super-classes are also available. 
     */
    @SuppressWarnings("hiding")
    public static final URI[] MANAGED_URIS = {
      new URIImpl("http://www.isa.us.es/preferences#hasRuleConclusion",false),
      new URIImpl("http://www.isa.us.es/preferences#hasRulePremise",false) 
    };


	// protected constructors needed for inheritance
	
	/**
	 * Returns a Java wrapper over an RDF object, identified by URI.
	 * Creating two wrappers for the same instanceURI is legal.
	 * @param model RDF2GO Model implementation, see http://rdf2go.semweb4j.org
	 * @param classURI URI of RDFS class
	 * @param instanceIdentifier Resource that identifies this instance
	 * @param write if true, the statement (this, rdf:type, TYPE) is written to the model
	 *
	 * [Generated from RDFReactor template rule #c1] 
	 */
	protected FuzzyRulePreference ( Model model, URI classURI, org.ontoware.rdf2go.model.node.Resource instanceIdentifier, boolean write ) {
		super(model, classURI, instanceIdentifier, write);
	}

	// public constructors

	/**
	 * Returns a Java wrapper over an RDF object, identified by URI.
	 * Creating two wrappers for the same instanceURI is legal.
	 * @param model RDF2GO Model implementation, see http://rdf2go.ontoware.org
	 * @param instanceIdentifier an RDF2Go Resource identifying this instance
	 * @param write if true, the statement (this, rdf:type, TYPE) is written to the model
	 *
	 * [Generated from RDFReactor template rule #c2] 
	 */
	public FuzzyRulePreference ( Model model, org.ontoware.rdf2go.model.node.Resource instanceIdentifier, boolean write ) {
		super(model, RDFS_CLASS, instanceIdentifier, write);
	}


	/**
	 * Returns a Java wrapper over an RDF object, identified by a URI, given as a String.
	 * Creating two wrappers for the same URI is legal.
	 * @param model RDF2GO Model implementation, see http://rdf2go.ontoware.org
	 * @param uriString a URI given as a String
	 * @param write if true, the statement (this, rdf:type, TYPE) is written to the model
	 * @throws ModelRuntimeException if URI syntax is wrong
	 *
	 * [Generated from RDFReactor template rule #c7] 
	 */
	public FuzzyRulePreference ( Model model, String uriString, boolean write) throws ModelRuntimeException {
		super(model, RDFS_CLASS, new URIImpl(uriString,false), write);
	}

	/**
	 * Returns a Java wrapper over an RDF object, identified by a blank node.
	 * Creating two wrappers for the same blank node is legal.
	 * @param model RDF2GO Model implementation, see http://rdf2go.ontoware.org
	 * @param bnode BlankNode of this instance
	 * @param write if true, the statement (this, rdf:type, TYPE) is written to the model
	 *
	 * [Generated from RDFReactor template rule #c8] 
	 */
	public FuzzyRulePreference ( Model model, BlankNode bnode, boolean write ) {
		super(model, RDFS_CLASS, bnode, write);
	}

	/**
	 * Returns a Java wrapper over an RDF object, identified by 
	 * a randomly generated URI.
	 * Creating two wrappers results in different URIs.
	 * @param model RDF2GO Model implementation, see http://rdf2go.ontoware.org
	 * @param write if true, the statement (this, rdf:type, TYPE) is written to the model
	 *
	 * [Generated from RDFReactor template rule #c9] 
	 */
	public FuzzyRulePreference ( Model model, boolean write ) {
		super(model, RDFS_CLASS, model.newRandomUniqueURI(), write);
	}

    ///////////////////////////////////////////////////////////////////
    // typing

	/**
	 * Return an existing instance of this class in the model. No statements are written.
	 * @param model an RDF2Go model
	 * @param instanceResource an RDF2Go resource
	 * @return an instance of FuzzyRulePreference  or null if none existst
	 *
	 * [Generated from RDFReactor template rule #class0] 
	 */
	public static FuzzyRulePreference  getInstance(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getInstance(model, instanceResource, FuzzyRulePreference.class);
	}

	/**
	 * Create a new instance of this class in the model. 
	 * That is, create the statement (instanceResource, RDF.type, http://www.isa.us.es/preferences#FuzzyRulePreference).
	 * @param model an RDF2Go model
	 * @param instanceResource an RDF2Go resource
	 *
	 * [Generated from RDFReactor template rule #class1] 
	 */
	public static void createInstance(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		Base.createInstance(model, RDFS_CLASS, instanceResource);
	}

	/**
	 * @param model an RDF2Go model
	 * @param instanceResource an RDF2Go resource
	 * @return true if instanceResource is an instance of this class in the model
	 *
	 * [Generated from RDFReactor template rule #class2] 
	 */
	public static boolean hasInstance(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.hasInstance(model, RDFS_CLASS, instanceResource);
	}

	/**
	 * @param model an RDF2Go model
	 * @return all instances of this class in Model 'model' as RDF resources
	 *
	 * [Generated from RDFReactor template rule #class3] 
	 */
	public static ClosableIterator<org.ontoware.rdf2go.model.node.Resource> getAllInstances(Model model) {
		return Base.getAllInstances(model, RDFS_CLASS, org.ontoware.rdf2go.model.node.Resource.class);
	}

	/**
	 * @param model an RDF2Go model
	 * @return all instances of this class in Model 'model' as a ReactorResult,
	 * which can conveniently be converted to iterator, list or array.
	 *
	 * [Generated from RDFReactor template rule #class3-as] 
	 */
	public static ReactorResult<? extends FuzzyRulePreference> getAllInstances_as(Model model) {
		return Base.getAllInstances_as(model, RDFS_CLASS, FuzzyRulePreference.class );
	}

    /**
	 * Remove rdf:type FuzzyRulePreference from this instance. Other triples are not affected.
	 * To delete more, use deleteAllProperties
	 * @param model an RDF2Go model
	 * @param instanceResource an RDF2Go resource
	 *
	 * [Generated from RDFReactor template rule #class4] 
	 */
	public static void deleteInstance(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		Base.deleteInstance(model, RDFS_CLASS, instanceResource);
	}

	/**
	 * Delete all (this, *, *), i.e. including rdf:type
	 * @param model an RDF2Go model
	 * @param resource
	 */
	public static void deleteAllProperties(Model model,	org.ontoware.rdf2go.model.node.Resource instanceResource) {
		Base.deleteAllProperties(model, instanceResource);
	}

    ///////////////////////////////////////////////////////////////////
    // property access methods


    /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@3563739 has at least one value set 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return true if this property has at least one value
	 *
	 * [Generated from RDFReactor template rule #get0has-static] 
     */
	public static boolean hasPrefHasRuleConclusion(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.has(model, instanceResource, HASRULECONCLUSION);
	}

    /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@3563739 has at least one value set 
     * @return true if this property has at least one value
	 *
	 * [Generated from RDFReactor template rule #get0has-dynamic] 
     */
	public boolean hasPrefHasRuleConclusion() {
		return Base.has(this.model, this.getResource(), HASRULECONCLUSION);
	}

    /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@3563739 has the given value (maybe among other values).  
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be checked
     * @return true if this property contains (maybe among other) the given value
	 *
	 * [Generated from RDFReactor template rule #get0has-value-static] 
     */
	public static boolean hasPrefHasRuleConclusion(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value ) {
		return Base.hasValue(model, instanceResource, HASRULECONCLUSION);
	}

    /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@3563739 has the given value (maybe among other values).  
	 * @param value the value to be checked
     * @return true if this property contains (maybe among other) the given value
	 *
	 * [Generated from RDFReactor template rule #get0has-value-dynamic] 
     */
	public boolean hasPrefHasRuleConclusion( org.ontoware.rdf2go.model.node.Node value ) {
		return Base.hasValue(this.model, this.getResource(), HASRULECONCLUSION);
	}

     /**
     * Get all values of property HasRuleConclusion as an Iterator over RDF2Go nodes 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a ClosableIterator of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get7static] 
     */
	public static ClosableIterator<org.ontoware.rdf2go.model.node.Node> getAllPrefHasRuleConclusion_asNode(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll_asNode(model, instanceResource, HASRULECONCLUSION);
	}
	
    /**
     * Get all values of property HasRuleConclusion as a ReactorResult of RDF2Go nodes 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a List of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get7static-reactor-result] 
     */
	public static ReactorResult<org.ontoware.rdf2go.model.node.Node> getAllPrefHasRuleConclusion_asNode_(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll_as(model, instanceResource, HASRULECONCLUSION, org.ontoware.rdf2go.model.node.Node.class);
	}

    /**
     * Get all values of property HasRuleConclusion as an Iterator over RDF2Go nodes 
     * @return a ClosableIterator of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get8dynamic] 
     */
	public ClosableIterator<org.ontoware.rdf2go.model.node.Node> getAllPrefHasRuleConclusion_asNode() {
		return Base.getAll_asNode(this.model, this.getResource(), HASRULECONCLUSION);
	}

    /**
     * Get all values of property HasRuleConclusion as a ReactorResult of RDF2Go nodes 
     * @return a List of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get8dynamic-reactor-result] 
     */
	public ReactorResult<org.ontoware.rdf2go.model.node.Node> getAllPrefHasRuleConclusion_asNode_() {
		return Base.getAll_as(this.model, this.getResource(), HASRULECONCLUSION, org.ontoware.rdf2go.model.node.Node.class);
	}
     /**
     * Get all values of property HasRuleConclusion     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a ClosableIterator of $type
	 *
	 * [Generated from RDFReactor template rule #get11static] 
     */
	public static ClosableIterator<PreferenceTerm> getAllPrefHasRuleConclusion(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll(model, instanceResource, HASRULECONCLUSION, PreferenceTerm.class);
	}
	
    /**
     * Get all values of property HasRuleConclusion as a ReactorResult of PreferenceTerm 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a ReactorResult of $type which can conveniently be converted to iterator, list or array
	 *
	 * [Generated from RDFReactor template rule #get11static-reactorresult] 
     */
	public static ReactorResult<PreferenceTerm> getAllPrefHasRuleConclusion_as(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll_as(model, instanceResource, HASRULECONCLUSION, PreferenceTerm.class);
	}

    /**
     * Get all values of property HasRuleConclusion     * @return a ClosableIterator of $type
	 *
	 * [Generated from RDFReactor template rule #get12dynamic] 
     */
	public ClosableIterator<PreferenceTerm> getAllPrefHasRuleConclusion() {
		return Base.getAll(this.model, this.getResource(), HASRULECONCLUSION, PreferenceTerm.class);
	}

    /**
     * Get all values of property HasRuleConclusion as a ReactorResult of PreferenceTerm 
     * @return a ReactorResult of $type which can conveniently be converted to iterator, list or array
	 *
	 * [Generated from RDFReactor template rule #get12dynamic-reactorresult] 
     */
	public ReactorResult<PreferenceTerm> getAllPrefHasRuleConclusion_as() {
		return Base.getAll_as(this.model, this.getResource(), HASRULECONCLUSION, PreferenceTerm.class);
	}
 
    /**
     * Adds a value to property HasRuleConclusion as an RDF2Go node 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #add1static] 
     */
	public static void addPrefHasRuleConclusion( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value) {
		Base.add(model, instanceResource, HASRULECONCLUSION, value);
	}
	
    /**
     * Adds a value to property HasRuleConclusion as an RDF2Go node 
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #add1dynamic] 
     */
	public void addPrefHasRuleConclusion( org.ontoware.rdf2go.model.node.Node value) {
		Base.add(this.model, this.getResource(), HASRULECONCLUSION, value);
	}
    /**
     * Adds a value to property HasRuleConclusion from an instance of PreferenceTerm 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 *
	 * [Generated from RDFReactor template rule #add3static] 
     */
	public static void addPrefHasRuleConclusion(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, PreferenceTerm value) {
		Base.add(model, instanceResource, HASRULECONCLUSION, value);
	}
	
    /**
     * Adds a value to property HasRuleConclusion from an instance of PreferenceTerm 
	 *
	 * [Generated from RDFReactor template rule #add4dynamic] 
     */
	public void addPrefHasRuleConclusion(PreferenceTerm value) {
		Base.add(this.model, this.getResource(), HASRULECONCLUSION, value);
	}
  

    /**
     * Sets a value of property HasRuleConclusion from an RDF2Go node.
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be set
	 *
	 * [Generated from RDFReactor template rule #set1static] 
     */
	public static void setPrefHasRuleConclusion( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value) {
		Base.set(model, instanceResource, HASRULECONCLUSION, value);
	}
	
    /**
     * Sets a value of property HasRuleConclusion from an RDF2Go node.
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #set1dynamic] 
     */
	public void setPrefHasRuleConclusion( org.ontoware.rdf2go.model.node.Node value) {
		Base.set(this.model, this.getResource(), HASRULECONCLUSION, value);
	}
    /**
     * Sets a value of property HasRuleConclusion from an instance of PreferenceTerm 
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #set3static] 
     */
	public static void setPrefHasRuleConclusion(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, PreferenceTerm value) {
		Base.set(model, instanceResource, HASRULECONCLUSION, value);
	}
	
    /**
     * Sets a value of property HasRuleConclusion from an instance of PreferenceTerm 
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #set4dynamic] 
     */
	public void setPrefHasRuleConclusion(PreferenceTerm value) {
		Base.set(this.model, this.getResource(), HASRULECONCLUSION, value);
	}
  


    /**
     * Removes a value of property HasRuleConclusion as an RDF2Go node 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove1static] 
     */
	public static void removePrefHasRuleConclusion( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value) {
		Base.remove(model, instanceResource, HASRULECONCLUSION, value);
	}
	
    /**
     * Removes a value of property HasRuleConclusion as an RDF2Go node
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove1dynamic] 
     */
	public void removePrefHasRuleConclusion( org.ontoware.rdf2go.model.node.Node value) {
		Base.remove(this.model, this.getResource(), HASRULECONCLUSION, value);
	}
    /**
     * Removes a value of property HasRuleConclusion given as an instance of PreferenceTerm 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove3static] 
     */
	public static void removePrefHasRuleConclusion(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, PreferenceTerm value) {
		Base.remove(model, instanceResource, HASRULECONCLUSION, value);
	}
	
    /**
     * Removes a value of property HasRuleConclusion given as an instance of PreferenceTerm 
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove4dynamic] 
     */
	public void removePrefHasRuleConclusion(PreferenceTerm value) {
		Base.remove(this.model, this.getResource(), HASRULECONCLUSION, value);
	}
  
    /**
     * Removes all values of property HasRuleConclusion     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 *
	 * [Generated from RDFReactor template rule #removeall1static] 
     */
	public static void removeAllPrefHasRuleConclusion( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		Base.removeAll(model, instanceResource, HASRULECONCLUSION);
	}
	
    /**
     * Removes all values of property HasRuleConclusion	 *
	 * [Generated from RDFReactor template rule #removeall1dynamic] 
     */
	public void removeAllPrefHasRuleConclusion() {
		Base.removeAll(this.model, this.getResource(), HASRULECONCLUSION);
	}
     /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@2e4ce3f8 has at least one value set 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return true if this property has at least one value
	 *
	 * [Generated from RDFReactor template rule #get0has-static] 
     */
	public static boolean hasPrefHasRulePremise(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.has(model, instanceResource, HASRULEPREMISE);
	}

    /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@2e4ce3f8 has at least one value set 
     * @return true if this property has at least one value
	 *
	 * [Generated from RDFReactor template rule #get0has-dynamic] 
     */
	public boolean hasPrefHasRulePremise() {
		return Base.has(this.model, this.getResource(), HASRULEPREMISE);
	}

    /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@2e4ce3f8 has the given value (maybe among other values).  
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be checked
     * @return true if this property contains (maybe among other) the given value
	 *
	 * [Generated from RDFReactor template rule #get0has-value-static] 
     */
	public static boolean hasPrefHasRulePremise(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value ) {
		return Base.hasValue(model, instanceResource, HASRULEPREMISE);
	}

    /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@2e4ce3f8 has the given value (maybe among other values).  
	 * @param value the value to be checked
     * @return true if this property contains (maybe among other) the given value
	 *
	 * [Generated from RDFReactor template rule #get0has-value-dynamic] 
     */
	public boolean hasPrefHasRulePremise( org.ontoware.rdf2go.model.node.Node value ) {
		return Base.hasValue(this.model, this.getResource(), HASRULEPREMISE);
	}

     /**
     * Get all values of property HasRulePremise as an Iterator over RDF2Go nodes 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a ClosableIterator of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get7static] 
     */
	public static ClosableIterator<org.ontoware.rdf2go.model.node.Node> getAllPrefHasRulePremise_asNode(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll_asNode(model, instanceResource, HASRULEPREMISE);
	}
	
    /**
     * Get all values of property HasRulePremise as a ReactorResult of RDF2Go nodes 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a List of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get7static-reactor-result] 
     */
	public static ReactorResult<org.ontoware.rdf2go.model.node.Node> getAllPrefHasRulePremise_asNode_(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll_as(model, instanceResource, HASRULEPREMISE, org.ontoware.rdf2go.model.node.Node.class);
	}

    /**
     * Get all values of property HasRulePremise as an Iterator over RDF2Go nodes 
     * @return a ClosableIterator of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get8dynamic] 
     */
	public ClosableIterator<org.ontoware.rdf2go.model.node.Node> getAllPrefHasRulePremise_asNode() {
		return Base.getAll_asNode(this.model, this.getResource(), HASRULEPREMISE);
	}

    /**
     * Get all values of property HasRulePremise as a ReactorResult of RDF2Go nodes 
     * @return a List of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get8dynamic-reactor-result] 
     */
	public ReactorResult<org.ontoware.rdf2go.model.node.Node> getAllPrefHasRulePremise_asNode_() {
		return Base.getAll_as(this.model, this.getResource(), HASRULEPREMISE, org.ontoware.rdf2go.model.node.Node.class);
	}
     /**
     * Get all values of property HasRulePremise     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a ClosableIterator of $type
	 *
	 * [Generated from RDFReactor template rule #get11static] 
     */
	public static ClosableIterator<PreferenceTerm> getAllPrefHasRulePremise(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll(model, instanceResource, HASRULEPREMISE, PreferenceTerm.class);
	}
	
    /**
     * Get all values of property HasRulePremise as a ReactorResult of PreferenceTerm 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a ReactorResult of $type which can conveniently be converted to iterator, list or array
	 *
	 * [Generated from RDFReactor template rule #get11static-reactorresult] 
     */
	public static ReactorResult<PreferenceTerm> getAllPrefHasRulePremise_as(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll_as(model, instanceResource, HASRULEPREMISE, PreferenceTerm.class);
	}

    /**
     * Get all values of property HasRulePremise     * @return a ClosableIterator of $type
	 *
	 * [Generated from RDFReactor template rule #get12dynamic] 
     */
	public ClosableIterator<PreferenceTerm> getAllPrefHasRulePremise() {
		return Base.getAll(this.model, this.getResource(), HASRULEPREMISE, PreferenceTerm.class);
	}

    /**
     * Get all values of property HasRulePremise as a ReactorResult of PreferenceTerm 
     * @return a ReactorResult of $type which can conveniently be converted to iterator, list or array
	 *
	 * [Generated from RDFReactor template rule #get12dynamic-reactorresult] 
     */
	public ReactorResult<PreferenceTerm> getAllPrefHasRulePremise_as() {
		return Base.getAll_as(this.model, this.getResource(), HASRULEPREMISE, PreferenceTerm.class);
	}
 
    /**
     * Adds a value to property HasRulePremise as an RDF2Go node 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #add1static] 
     */
	public static void addPrefHasRulePremise( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value) {
		Base.add(model, instanceResource, HASRULEPREMISE, value);
	}
	
    /**
     * Adds a value to property HasRulePremise as an RDF2Go node 
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #add1dynamic] 
     */
	public void addPrefHasRulePremise( org.ontoware.rdf2go.model.node.Node value) {
		Base.add(this.model, this.getResource(), HASRULEPREMISE, value);
	}
    /**
     * Adds a value to property HasRulePremise from an instance of PreferenceTerm 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 *
	 * [Generated from RDFReactor template rule #add3static] 
     */
	public static void addPrefHasRulePremise(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, PreferenceTerm value) {
		Base.add(model, instanceResource, HASRULEPREMISE, value);
	}
	
    /**
     * Adds a value to property HasRulePremise from an instance of PreferenceTerm 
	 *
	 * [Generated from RDFReactor template rule #add4dynamic] 
     */
	public void addPrefHasRulePremise(PreferenceTerm value) {
		Base.add(this.model, this.getResource(), HASRULEPREMISE, value);
	}
  

    /**
     * Sets a value of property HasRulePremise from an RDF2Go node.
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be set
	 *
	 * [Generated from RDFReactor template rule #set1static] 
     */
	public static void setPrefHasRulePremise( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value) {
		Base.set(model, instanceResource, HASRULEPREMISE, value);
	}
	
    /**
     * Sets a value of property HasRulePremise from an RDF2Go node.
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #set1dynamic] 
     */
	public void setPrefHasRulePremise( org.ontoware.rdf2go.model.node.Node value) {
		Base.set(this.model, this.getResource(), HASRULEPREMISE, value);
	}
    /**
     * Sets a value of property HasRulePremise from an instance of PreferenceTerm 
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #set3static] 
     */
	public static void setPrefHasRulePremise(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, PreferenceTerm value) {
		Base.set(model, instanceResource, HASRULEPREMISE, value);
	}
	
    /**
     * Sets a value of property HasRulePremise from an instance of PreferenceTerm 
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #set4dynamic] 
     */
	public void setPrefHasRulePremise(PreferenceTerm value) {
		Base.set(this.model, this.getResource(), HASRULEPREMISE, value);
	}
  


    /**
     * Removes a value of property HasRulePremise as an RDF2Go node 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove1static] 
     */
	public static void removePrefHasRulePremise( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value) {
		Base.remove(model, instanceResource, HASRULEPREMISE, value);
	}
	
    /**
     * Removes a value of property HasRulePremise as an RDF2Go node
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove1dynamic] 
     */
	public void removePrefHasRulePremise( org.ontoware.rdf2go.model.node.Node value) {
		Base.remove(this.model, this.getResource(), HASRULEPREMISE, value);
	}
    /**
     * Removes a value of property HasRulePremise given as an instance of PreferenceTerm 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove3static] 
     */
	public static void removePrefHasRulePremise(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, PreferenceTerm value) {
		Base.remove(model, instanceResource, HASRULEPREMISE, value);
	}
	
    /**
     * Removes a value of property HasRulePremise given as an instance of PreferenceTerm 
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove4dynamic] 
     */
	public void removePrefHasRulePremise(PreferenceTerm value) {
		Base.remove(this.model, this.getResource(), HASRULEPREMISE, value);
	}
  
    /**
     * Removes all values of property HasRulePremise     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 *
	 * [Generated from RDFReactor template rule #removeall1static] 
     */
	public static void removeAllPrefHasRulePremise( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		Base.removeAll(model, instanceResource, HASRULEPREMISE);
	}
	
    /**
     * Removes all values of property HasRulePremise	 *
	 * [Generated from RDFReactor template rule #removeall1dynamic] 
     */
	public void removeAllPrefHasRulePremise() {
		Base.removeAll(this.model, this.getResource(), HASRULEPREMISE);
	}
 }